// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGz32_Zfm-HriKIMjlTWQqQl1wuZbDOZU',
    appId: '1:600591630798:web:90c45cc1b0411fa637eb9f',
    messagingSenderId: '600591630798',
    projectId: 'keyrank-flutter',
    authDomain: 'keyrank-flutter.firebaseapp.com',
    storageBucket: 'keyrank-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYL8Tq2yHgJDoRKejw-yTGMsRG1cTJ7A8',
    appId: '1:600591630798:android:c861bc46afaa412f37eb9f',
    messagingSenderId: '600591630798',
    projectId: 'keyrank-flutter',
    storageBucket: 'keyrank-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaDoSs-_Hqb3U3IA5ncaO9rsakWT2-WPM',
    appId: '1:600591630798:ios:5af52aa84e38e63a37eb9f',
    messagingSenderId: '600591630798',
    projectId: 'keyrank-flutter',
    storageBucket: 'keyrank-flutter.firebasestorage.app',
    iosBundleId: 'com.ranking.asoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaDoSs-_Hqb3U3IA5ncaO9rsakWT2-WPM',
    appId: '1:600591630798:ios:5af52aa84e38e63a37eb9f',
    messagingSenderId: '600591630798',
    projectId: 'keyrank-flutter',
    storageBucket: 'keyrank-flutter.firebasestorage.app',
    iosBundleId: 'com.ranking.asoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGz32_Zfm-HriKIMjlTWQqQl1wuZbDOZU',
    appId: '1:600591630798:web:b80f335d1b8329b937eb9f',
    messagingSenderId: '600591630798',
    projectId: 'keyrank-flutter',
    authDomain: 'keyrank-flutter.firebaseapp.com',
    storageBucket: 'keyrank-flutter.firebasestorage.app',
  );
}
