import 'package:flutter/widgets.dart';

/// Localized country names for App Store storefronts
const _localizedCountryNames = {
  'en': {
    'US': 'United States',
    'GB': 'United Kingdom',
    'FR': 'France',
    'DE': 'Germany',
    'JP': 'Japan',
    'CN': 'China',
    'KR': 'South Korea',
    'AU': 'Australia',
    'CA': 'Canada',
    'IT': 'Italy',
    'ES': 'Spain',
    'NL': 'Netherlands',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'RU': 'Russia',
    'IN': 'India',
    'SE': 'Sweden',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'CH': 'Switzerland',
    'AT': 'Austria',
    'BE': 'Belgium',
    'PT': 'Portugal',
    'PL': 'Poland',
    'SG': 'Singapore',
    'HK': 'Hong Kong',
    'TW': 'Taiwan',
    'TH': 'Thailand',
    'ID': 'Indonesia',
    'MY': 'Malaysia',
    'PH': 'Philippines',
    'VN': 'Vietnam',
    'ZA': 'South Africa',
    'AE': 'United Arab Emirates',
    'SA': 'Saudi Arabia',
    'TR': 'Turkey',
    'IL': 'Israel',
    'EG': 'Egypt',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'PE': 'Peru',
    'NZ': 'New Zealand',
  },
  'fr': {
    'US': 'États-Unis',
    'GB': 'Royaume-Uni',
    'FR': 'France',
    'DE': 'Allemagne',
    'JP': 'Japon',
    'CN': 'Chine',
    'KR': 'Corée du Sud',
    'AU': 'Australie',
    'CA': 'Canada',
    'IT': 'Italie',
    'ES': 'Espagne',
    'NL': 'Pays-Bas',
    'BR': 'Brésil',
    'MX': 'Mexique',
    'RU': 'Russie',
    'IN': 'Inde',
    'SE': 'Suède',
    'NO': 'Norvège',
    'DK': 'Danemark',
    'FI': 'Finlande',
    'CH': 'Suisse',
    'AT': 'Autriche',
    'BE': 'Belgique',
    'PT': 'Portugal',
    'PL': 'Pologne',
    'SG': 'Singapour',
    'HK': 'Hong Kong',
    'TW': 'Taïwan',
    'TH': 'Thaïlande',
    'ID': 'Indonésie',
    'MY': 'Malaisie',
    'PH': 'Philippines',
    'VN': 'Viêt Nam',
    'ZA': 'Afrique du Sud',
    'AE': 'Émirats arabes unis',
    'SA': 'Arabie saoudite',
    'TR': 'Turquie',
    'IL': 'Israël',
    'EG': 'Égypte',
    'AR': 'Argentine',
    'CL': 'Chili',
    'CO': 'Colombie',
    'PE': 'Pérou',
    'NZ': 'Nouvelle-Zélande',
  },
  'de': {
    'US': 'Vereinigte Staaten',
    'GB': 'Vereinigtes Königreich',
    'FR': 'Frankreich',
    'DE': 'Deutschland',
    'JP': 'Japan',
    'CN': 'China',
    'KR': 'Südkorea',
    'AU': 'Australien',
    'CA': 'Kanada',
    'IT': 'Italien',
    'ES': 'Spanien',
    'NL': 'Niederlande',
    'BR': 'Brasilien',
    'MX': 'Mexiko',
    'RU': 'Russland',
    'IN': 'Indien',
    'SE': 'Schweden',
    'NO': 'Norwegen',
    'DK': 'Dänemark',
    'FI': 'Finnland',
    'CH': 'Schweiz',
    'AT': 'Österreich',
    'BE': 'Belgien',
    'PT': 'Portugal',
    'PL': 'Polen',
    'SG': 'Singapur',
    'HK': 'Hongkong',
    'TW': 'Taiwan',
    'TH': 'Thailand',
    'ID': 'Indonesien',
    'MY': 'Malaysia',
    'PH': 'Philippinen',
    'VN': 'Vietnam',
    'ZA': 'Südafrika',
    'AE': 'Vereinigte Arabische Emirate',
    'SA': 'Saudi-Arabien',
    'TR': 'Türkei',
    'IL': 'Israel',
    'EG': 'Ägypten',
    'AR': 'Argentinien',
    'CL': 'Chile',
    'CO': 'Kolumbien',
    'PE': 'Peru',
    'NZ': 'Neuseeland',
  },
  'es': {
    'US': 'Estados Unidos',
    'GB': 'Reino Unido',
    'FR': 'Francia',
    'DE': 'Alemania',
    'JP': 'Japón',
    'CN': 'China',
    'KR': 'Corea del Sur',
    'AU': 'Australia',
    'CA': 'Canadá',
    'IT': 'Italia',
    'ES': 'España',
    'NL': 'Países Bajos',
    'BR': 'Brasil',
    'MX': 'México',
    'RU': 'Rusia',
    'IN': 'India',
    'SE': 'Suecia',
    'NO': 'Noruega',
    'DK': 'Dinamarca',
    'FI': 'Finlandia',
    'CH': 'Suiza',
    'AT': 'Austria',
    'BE': 'Bélgica',
    'PT': 'Portugal',
    'PL': 'Polonia',
    'SG': 'Singapur',
    'HK': 'Hong Kong',
    'TW': 'Taiwán',
    'TH': 'Tailandia',
    'ID': 'Indonesia',
    'MY': 'Malasia',
    'PH': 'Filipinas',
    'VN': 'Vietnam',
    'ZA': 'Sudáfrica',
    'AE': 'Emiratos Árabes Unidos',
    'SA': 'Arabia Saudita',
    'TR': 'Turquía',
    'IL': 'Israel',
    'EG': 'Egipto',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'PE': 'Perú',
    'NZ': 'Nueva Zelanda',
  },
  'it': {
    'US': 'Stati Uniti',
    'GB': 'Regno Unito',
    'FR': 'Francia',
    'DE': 'Germania',
    'JP': 'Giappone',
    'CN': 'Cina',
    'KR': 'Corea del Sud',
    'AU': 'Australia',
    'CA': 'Canada',
    'IT': 'Italia',
    'ES': 'Spagna',
    'NL': 'Paesi Bassi',
    'BR': 'Brasile',
    'MX': 'Messico',
    'RU': 'Russia',
    'IN': 'India',
    'SE': 'Svezia',
    'NO': 'Norvegia',
    'DK': 'Danimarca',
    'FI': 'Finlandia',
    'CH': 'Svizzera',
    'AT': 'Austria',
    'BE': 'Belgio',
    'PT': 'Portogallo',
    'PL': 'Polonia',
    'SG': 'Singapore',
    'HK': 'Hong Kong',
    'TW': 'Taiwan',
    'TH': 'Thailandia',
    'ID': 'Indonesia',
    'MY': 'Malesia',
    'PH': 'Filippine',
    'VN': 'Vietnam',
    'ZA': 'Sudafrica',
    'AE': 'Emirati Arabi Uniti',
    'SA': 'Arabia Saudita',
    'TR': 'Turchia',
    'IL': 'Israele',
    'EG': 'Egitto',
    'AR': 'Argentina',
    'CL': 'Cile',
    'CO': 'Colombia',
    'PE': 'Perù',
    'NZ': 'Nuova Zelanda',
  },
  'pt': {
    'US': 'Estados Unidos',
    'GB': 'Reino Unido',
    'FR': 'França',
    'DE': 'Alemanha',
    'JP': 'Japão',
    'CN': 'China',
    'KR': 'Coreia do Sul',
    'AU': 'Austrália',
    'CA': 'Canadá',
    'IT': 'Itália',
    'ES': 'Espanha',
    'NL': 'Países Baixos',
    'BR': 'Brasil',
    'MX': 'México',
    'RU': 'Rússia',
    'IN': 'Índia',
    'SE': 'Suécia',
    'NO': 'Noruega',
    'DK': 'Dinamarca',
    'FI': 'Finlândia',
    'CH': 'Suíça',
    'AT': 'Áustria',
    'BE': 'Bélgica',
    'PT': 'Portugal',
    'PL': 'Polônia',
    'SG': 'Singapura',
    'HK': 'Hong Kong',
    'TW': 'Taiwan',
    'TH': 'Tailândia',
    'ID': 'Indonésia',
    'MY': 'Malásia',
    'PH': 'Filipinas',
    'VN': 'Vietnã',
    'ZA': 'África do Sul',
    'AE': 'Emirados Árabes Unidos',
    'SA': 'Arábia Saudita',
    'TR': 'Turquia',
    'IL': 'Israel',
    'EG': 'Egito',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colômbia',
    'PE': 'Peru',
    'NZ': 'Nova Zelândia',
  },
  'ja': {
    'US': 'アメリカ合衆国',
    'GB': 'イギリス',
    'FR': 'フランス',
    'DE': 'ドイツ',
    'JP': '日本',
    'CN': '中国',
    'KR': '韓国',
    'AU': 'オーストラリア',
    'CA': 'カナダ',
    'IT': 'イタリア',
    'ES': 'スペイン',
    'NL': 'オランダ',
    'BR': 'ブラジル',
    'MX': 'メキシコ',
    'RU': 'ロシア',
    'IN': 'インド',
    'SE': 'スウェーデン',
    'NO': 'ノルウェー',
    'DK': 'デンマーク',
    'FI': 'フィンランド',
    'CH': 'スイス',
    'AT': 'オーストリア',
    'BE': 'ベルギー',
    'PT': 'ポルトガル',
    'PL': 'ポーランド',
    'SG': 'シンガポール',
    'HK': '香港',
    'TW': '台湾',
    'TH': 'タイ',
    'ID': 'インドネシア',
    'MY': 'マレーシア',
    'PH': 'フィリピン',
    'VN': 'ベトナム',
    'ZA': '南アフリカ',
    'AE': 'アラブ首長国連邦',
    'SA': 'サウジアラビア',
    'TR': 'トルコ',
    'IL': 'イスラエル',
    'EG': 'エジプト',
    'AR': 'アルゼンチン',
    'CL': 'チリ',
    'CO': 'コロンビア',
    'PE': 'ペルー',
    'NZ': 'ニュージーランド',
  },
  'ko': {
    'US': '미국',
    'GB': '영국',
    'FR': '프랑스',
    'DE': '독일',
    'JP': '일본',
    'CN': '중국',
    'KR': '대한민국',
    'AU': '호주',
    'CA': '캐나다',
    'IT': '이탈리아',
    'ES': '스페인',
    'NL': '네덜란드',
    'BR': '브라질',
    'MX': '멕시코',
    'RU': '러시아',
    'IN': '인도',
    'SE': '스웨덴',
    'NO': '노르웨이',
    'DK': '덴마크',
    'FI': '핀란드',
    'CH': '스위스',
    'AT': '오스트리아',
    'BE': '벨기에',
    'PT': '포르투갈',
    'PL': '폴란드',
    'SG': '싱가포르',
    'HK': '홍콩',
    'TW': '대만',
    'TH': '태국',
    'ID': '인도네시아',
    'MY': '말레이시아',
    'PH': '필리핀',
    'VN': '베트남',
    'ZA': '남아프리카 공화국',
    'AE': '아랍에미리트',
    'SA': '사우디아라비아',
    'TR': '터키',
    'IL': '이스라엘',
    'EG': '이집트',
    'AR': '아르헨티나',
    'CL': '칠레',
    'CO': '콜롬비아',
    'PE': '페루',
    'NZ': '뉴질랜드',
  },
  'zh': {
    'US': '美国',
    'GB': '英国',
    'FR': '法国',
    'DE': '德国',
    'JP': '日本',
    'CN': '中国',
    'KR': '韩国',
    'AU': '澳大利亚',
    'CA': '加拿大',
    'IT': '意大利',
    'ES': '西班牙',
    'NL': '荷兰',
    'BR': '巴西',
    'MX': '墨西哥',
    'RU': '俄罗斯',
    'IN': '印度',
    'SE': '瑞典',
    'NO': '挪威',
    'DK': '丹麦',
    'FI': '芬兰',
    'CH': '瑞士',
    'AT': '奥地利',
    'BE': '比利时',
    'PT': '葡萄牙',
    'PL': '波兰',
    'SG': '新加坡',
    'HK': '香港',
    'TW': '台湾',
    'TH': '泰国',
    'ID': '印度尼西亚',
    'MY': '马来西亚',
    'PH': '菲律宾',
    'VN': '越南',
    'ZA': '南非',
    'AE': '阿联酋',
    'SA': '沙特阿拉伯',
    'TR': '土耳其',
    'IL': '以色列',
    'EG': '埃及',
    'AR': '阿根廷',
    'CL': '智利',
    'CO': '哥伦比亚',
    'PE': '秘鲁',
    'NZ': '新西兰',
  },
  'tr': {
    'US': 'Amerika Birleşik Devletleri',
    'GB': 'Birleşik Krallık',
    'FR': 'Fransa',
    'DE': 'Almanya',
    'JP': 'Japonya',
    'CN': 'Çin',
    'KR': 'Güney Kore',
    'AU': 'Avustralya',
    'CA': 'Kanada',
    'IT': 'İtalya',
    'ES': 'İspanya',
    'NL': 'Hollanda',
    'BR': 'Brezilya',
    'MX': 'Meksika',
    'RU': 'Rusya',
    'IN': 'Hindistan',
    'SE': 'İsveç',
    'NO': 'Norveç',
    'DK': 'Danimarka',
    'FI': 'Finlandiya',
    'CH': 'İsviçre',
    'AT': 'Avusturya',
    'BE': 'Belçika',
    'PT': 'Portekiz',
    'PL': 'Polonya',
    'SG': 'Singapur',
    'HK': 'Hong Kong',
    'TW': 'Tayvan',
    'TH': 'Tayland',
    'ID': 'Endonezya',
    'MY': 'Malezya',
    'PH': 'Filipinler',
    'VN': 'Vietnam',
    'ZA': 'Güney Afrika',
    'AE': 'Birleşik Arap Emirlikleri',
    'SA': 'Suudi Arabistan',
    'TR': 'Türkiye',
    'IL': 'İsrail',
    'EG': 'Mısır',
    'AR': 'Arjantin',
    'CL': 'Şili',
    'CO': 'Kolombiya',
    'PE': 'Peru',
    'NZ': 'Yeni Zelanda',
  },
};

/// Get localized country name from country code.
/// Uses the app's locale to return the appropriate translation.
String getLocalizedCountryName(BuildContext context, String countryCode) {
  final code = countryCode.toUpperCase();
  final locale = Localizations.localeOf(context);
  final languageCode = locale.languageCode;

  // Try to get localized name for current language
  final localizedNames = _localizedCountryNames[languageCode];
  if (localizedNames != null && localizedNames.containsKey(code)) {
    return localizedNames[code]!;
  }

  // Fallback to English
  final englishNames = _localizedCountryNames['en'];
  if (englishNames != null && englishNames.containsKey(code)) {
    return englishNames[code]!;
  }

  // Final fallback: return the code itself
  return code;
}
